---
title: "MidtermStats"
author: "Lucas Forrest"
date: "11/10/2021"
output:
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Library Packages

```{r library}
library(readxl)
library(vioplot)
library(tidyverse)
```

## Import Data

```{r import}

gradedata <- read_excel("C:/Users/Lucas/OneDrive - Forrest/Work/UWT Lecturer/AU21 TBUS 301C/AU21 Midterm Grades.xlsx", sheet = "Grades")

surveydata <- read_excel("C:/Users/Lucas/OneDrive - Forrest/Work/UWT Lecturer/AU21 TBUS 301C/AU21 Midterm Grades.xlsx", 
    sheet = "Survey")
```

## Survey

```{r}
summary(surveydata$Hours)

boxplot(surveydata$Hours, col = "darkgoldenrod1", xlab = "Hours", horizontal = TRUE, main = "Time to Finish Midterm")

barplot(table(surveydata$EasiestQ), main = "Easiest Question")

barplot(table(surveydata$HardestQ), main = "Hardest Question")
```

## Question 1

```{r q1}
qcol1 <- c('P1', 'C1', 'T1')

vioplot(gradedata[, qcol1], col = c("skyblue3", "coral1", "darkgoldenrod1"), xlab = "Points", horizontal = TRUE)
```

## Question 2

```{r q2}
qcol2 <- c('P2', 'C2', 'T2')

vioplot(gradedata[, qcol2], col = c("skyblue3", "coral1", "darkgoldenrod1"), xlab = "Points", horizontal = TRUE)
```

## Question 3

```{r q3}
qcol3 <- c('P3', 'C3', 'T3')

vioplot(gradedata[, qcol3], col = c("skyblue3", "coral1", "darkgoldenrod1"), xlab = "Points", horizontal = TRUE)
```

## Question 4

```{r q4}
qcol4 <- c('P4', 'C4', 'T4')

vioplot(gradedata[, qcol4], col = c("skyblue3", "coral1", "darkgoldenrod1"), xlab = "Points", horizontal = TRUE)
```

## Question 5

```{r q5}
qcol5 <- c('P5', 'C5', 'T5')

vioplot(gradedata[, qcol5], col = c("skyblue3", "coral1", "darkgoldenrod1"), xlab = "Points", horizontal = TRUE)
```

## Question 6

```{r q6}
qcol6 <- c('P6', 'C6', 'T6')

vioplot(gradedata[, qcol6], col = c("skyblue3", "coral1", "darkgoldenrod1"), xlab = "Points", horizontal = TRUE)
```

## Question 7

```{r q7}
qcol7 <- c('P7', 'C7', 'T7')

vioplot(gradedata[, qcol7], col = c("skyblue3", "coral1", "darkgoldenrod1"), xlab = "Points", horizontal = TRUE)
```

## Question 8

```{r q8}
qcol8 <- c('P8', 'C8', 'T8')

vioplot(gradedata[, qcol8], col = c("skyblue3", "coral1", "darkgoldenrod1"), xlab = "Points", horizontal = TRUE)
```

## Question 9

```{r q9}
qcol9 <- c('P9', 'C9', 'T9')

vioplot(gradedata[, qcol9], col = c("skyblue3", "coral1", "darkgoldenrod1"), xlab = "Points", horizontal = TRUE)
```


## Adjustments

```{r Adj}
# To record point information
ppoints <- 57 # Raw practical points
cpoints <- 33 # Raw conceptual points
appoints <- 50 # Removes Q4p points
acpoints <- 30 # Removes Q4c points

# To remove question 4 values
gradedata$APRS <- gradedata$PRS - gradedata$`4a` - gradedata$`4b`
gradedata$ACRS <- gradedata$CRS - gradedata$`4c`
gradedata$TAS <- gradedata$APRS + gradedata$ACRS

# To add extra points, add back carry forward errors

gradedata$FPS <- gradedata$APRS + gradedata$PDPA
gradedata$FCS <- gradedata$ACRS + gradedata$CDPA
gradedata$FTS <- gradedata$FPS + gradedata$FCS + gradedata$EA

# To reweigh practical/conceptual
gradedata$TRP <- (gradedata$PRS / ppoints) * 0.70 + (gradedata$CRS / cpoints) * 0.30

gradedata$TAP <- (gradedata$APRS / appoints) * 0.70 + (gradedata$ACRS / acpoints) * 0.30

gradedata$TFP <- ((gradedata$FPS / appoints) * 0.70 + (gradedata$FCS / acpoints) * 0.30) + gradedata$EA / (appoints + acpoints)

```

## Scores

```{r Scores}

vioplot(gradedata[, c("TRS", "TAS", "FTS")], col = c("skyblue3", "coral1", "darkgoldenrod1"), xlab = "Points", horizontal = TRUE)

vioplot(gradedata[, c("TRP", "TAP", "TFP")], col = c("skyblue3", "coral1", "darkgoldenrod1"), xlab = "Percent", horizontal = TRUE)

```

## Summary

```{r}

summary(gradedata$TFP)

```

## Output

```{r output}

output <- data.frame(gradedata$Student, gradedata$FTS, gradedata$TFP)
View(output)

```